# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        Shm\UserBundle\Entity\User: bcrypt

    role_hierarchy:
        ROLE_EDITOR:  ROLE_USER
        ROLE_ADMIN:   [ROLE_USER, ROLE_EDITOR]

    providers:
        our_db_provider:
            entity:
                class: ShmUserBundle:User
                property: username

    firewalls:
#        admin_area:
#            pattern:    ^/admin
#            http_basic: ~

        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous: ~
            http_basic: ~
            provider: our_db_provider
            form_login:
                login_path: ShmUserBundle_loginpage
                check_path: ShmUserBundle_loginpage
#                default_target_path: ShmUserBundle_homepage

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/admin, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/, roles: ROLE_ADMIN }
