# src/Shm/UserBundle/Resources/config/routing.yml

shm_user_groups:
    resource: "@ShmUserBundle/Resources/config/routing/group.yml"
    prefix:   /groups

shm_user_users:
    resource: "@ShmUserBundle/Resources/config/routing/user.yml"
    prefix:   /users

ShmUserBundle_homepage:
  path: /
  defaults: { _controller: "ShmUserBundle:Page:index" }
  requirements:
    methods: GET

ShmUserBundle_accessdenied:
  path: /error403
  defaults: { _controller: "ShmUserBundle:Page:accessDenied" }
  requirements:
    methods: GET
