# src/Shm/UserBundle/Resources/config/routing.yml

ShmUserBundle_homepage:
  path: /
  defaults: { _controller: "ShmUserBundle:Page:index" }
  requirements:
    methods: GET

ShmUserBundle_users:
  path: /users/
  defaults: { _controller: "ShmUserBundle:Page:users" }
  requirements:
    methods: GET

ShmUserBundle_groups:
  path: /groups/
  defaults: { _controller: "ShmUserBundle:Page:groups" }
  requirements:
    methods: GET

ShmUserBundle_group_new:
  path: /groups/new/
  defaults: { _controller: "ShmUserBundle:Group:new" }
  requirements:
    methods: GET

ShmUserBundle_group_edit:
  path: /groups/{id}
  defaults: { _controller: "ShmUserBundle:Group:edit" }
  requirements:
    methods: GET
    id: \d+
