shm_user_groups:
    resource: "@ShmUserBundle/Resources/config/routing/group.yml"
    prefix:   /groups

shm_user_users:
    resource: "@ShmUserBundle/Resources/config/routing/user.yml"
    prefix:   /users

# src/Shm/UserBundle/Resources/config/routing.yml

ShmUserBundle_homepage:
  path: /
  defaults: { _controller: "ShmUserBundle:Page:index" }
  requirements:
    methods: GET

ShmUserBundle_adminpage:
  path: /admin
  defaults: { _controller: "ShmUserBundle:Page:admin" }
  requirements:
    methods: GET
