services:
    Shm\UserBundle\Controller\UserController:
         autowire: true # or define your controller constructor and configure its arguments explicitly
         tags: ['controller.service_arguments']
#    shm_user.example:
#        class: Shm\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
